import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ShieldCheck, Building2, Wallet, FolderKanban, ClipboardCheck, Users, Zap, Bell, MessageSquare, Settings, Landmark, Home, UserCheck } from 'lucide-react';
import './styles.css';

const API = '/api';
const modules = [
  ['Finance', Wallet], ['Projects', FolderKanban], ['Compliance', ClipboardCheck], ['People', Users], ['Estate', Building2], ['Energy', Zap], ['Operations', Activity], ['Customer', UserCheck]
];
function token(){ return localStorage.getItem('pulse_token'); }
async function api(path, opts={}){ const res = await fetch(API+path, { ...opts, headers:{ 'Content-Type':'application/json', ...(opts.headers||{}), ...(token()?{Authorization:`Bearer ${token()}`}:{}) }}); if(!res.ok){ throw new Error((await res.json()).error || 'Request failed'); } return res.json(); }
function currency(v){ return `£${Number(v||0).toLocaleString()}`; }

function Login({onLogin}){
  const [email,setEmail]=useState('owner@demo.local'), [password,setPassword]=useState('PulseOwner123!'), [mode,setMode]=useState('login'), [err,setErr]=useState('');
  const [form,setForm]=useState({name:'',company_name:'',company_number:'',director_email:''});
  async function submit(e){ e.preventDefault(); setErr(''); try { if(mode==='login'){ const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})}); localStorage.setItem('pulse_token',r.token); onLogin(r); } else { await api('/onboarding',{method:'POST',body:JSON.stringify({...form,email,password})}); setMode('pending'); } } catch(ex){ setErr(ex.message); }}
  if(mode==='pending') return <div className="auth"><div className="authCard"><Logo/><h1>Verification request submitted</h1><p>Your organisation is pending manual verification. A Pulse platform admin must upload the signed contract and mark the organisation as verified before modules unlock.</p><button onClick={()=>setMode('login')}>Back to login</button></div></div>;
  return <div className="auth"><div className="authCard"><Logo/><h1>{mode==='login'?'Welcome back':'Create your Pulse account'}</h1><p>Operational intelligence for modern businesses.</p><form onSubmit={submit}>{mode==='signup'&&<><input placeholder="Your name" onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Company name" onChange={e=>setForm({...form,company_name:e.target.value})}/><input placeholder="Companies House number" onChange={e=>setForm({...form,company_number:e.target.value})}/><input placeholder="Director email" onChange={e=>setForm({...form,director_email:e.target.value})}/></>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/>{err&&<div className="error">{err}</div>}<button>{mode==='login'?'Login':'Submit verification request'}</button></form><a onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create organisation':'Already have an account?'}</a><div className="demo">Demo: owner@demo.local / PulseOwner123!<br/>Admin: admin@pulse.local / PulseAdmin123!</div></div></div>
}
function Logo(){ return <div className="logo"><div className="pulseMark"><Activity size={22}/></div><b>Pulse</b></div> }
function Shell({me,onLogout}){ const [tab,setTab]=useState('Dashboard'); const admin=me.user.role==='platform_admin'; const items=admin?['Admin Centre','Audit Logs']:['Dashboard','Finance','Projects','Compliance','Notifications','Integrations','AI Concierge','Security']; return <div className="app"><aside><Logo/><nav>{items.map(i=><button className={tab===i?'active':''} onClick={()=>setTab(i)} key={i}>{i}</button>)}</nav><div className="user"><b>{me.user.name}</b><span>{me.user.role.replaceAll('_',' ')}</span><button onClick={onLogout}>Logout</button></div></aside><main><Top me={me}/>{admin?<Admin tab={tab}/>:<UserArea tab={tab}/>}</main></div> }
function Top({me}){ return <header><div><h1>{me.organisation?.name || 'Pulse Platform'}</h1><p>{me.organisation?.status || 'Platform administration'} · Security score {me.organisation?.security_score || 'A+'}</p></div><div className="pill"><ShieldCheck size={16}/> MFA {me.organisation?.mfa_required===0?'Optional':'Required'}</div></header> }
function UserArea({tab}){ if(tab==='Dashboard')return <Dashboard/>; if(tab==='Finance')return <Finance/>; if(tab==='Projects')return <Projects/>; if(tab==='Compliance')return <Compliance/>; if(tab==='Notifications')return <Notifications/>; if(tab==='Integrations')return <Integrations/>; if(tab==='AI Concierge')return <Concierge/>; return <Security/>; }
function Dashboard(){ const [data,setData]=useState(null); useEffect(()=>{api('/dashboard').then(setData)},[]); if(!data)return <Loader/>; return <><section className="hero"><h2>Good morning. Here is what needs attention.</h2><p>Pulse consolidates your source systems into a single operational intelligence layer.</p></section><div className="grid cards">{data.modules.map(m=>{ const Icon=(modules.find(x=>x[0]===m.name)||[])[1]||Activity; return <div className="card" key={m.name}><div className="cardHead"><Icon/><h3>{m.name}</h3></div><div className="kpis">{m.kpis.slice(0,3).map(k=><div key={k.id}><span>{k.label}</span><b>{k.value}</b><em className={k.risk}>{k.trend}</em></div>)}</div>{m.alerts[0]&&<div className="alert">{m.alerts[0].title}: {m.alerts[0].body}</div>}</div>})}</div></> }
function Finance(){ const [d,setD]=useState(null); useEffect(()=>{api('/finance').then(setD)},[]); if(!d)return <Loader/>; const incomeVar=d.sums.income.actual-d.sums.income.budget, expVar=d.sums.expense.actual-d.sums.expense.budget, profitVar=d.profitActual-d.profitBudget; return <><h2>Finance</h2><div className="metricRow"><Metric label="Income variance" value={currency(incomeVar)}/><Metric label="Expense variance" value={currency(expVar)}/><Metric label="Profit variance" value={currency(profitVar)}/></div><div className="card"><h3>AI Executive Summary</h3><p>{d.ai}</p></div><div className="card"><h3>Budget vs Forecast vs Actual</h3><table><thead><tr><th>Line</th><th>Type</th><th>Budget</th><th>Forecast</th><th>Actual</th></tr></thead><tbody>{d.lines.map(l=><tr key={l.id}><td>{l.label}</td><td>{l.type}</td><td>{currency(l.budget)}</td><td>{currency(l.forecast)}</td><td>{currency(l.actual)}</td></tr>)}</tbody></table></div></> }
function Projects(){ const [p,setP]=useState([]); useEffect(()=>{api('/projects').then(setP)},[]); return <><h2>Projects</h2><div className="grid">{p.map(x=><div className="card"><h3>{x.name}</h3><p>{x.category} {x.riba_stage?`· ${x.riba_stage}`:''}</p><span className={`status ${x.health.replaceAll(' ','')}`}>{x.health}</span><div className="kpis"><div><span>Budget</span><b>{currency(x.budget)}</b></div><div><span>Invoiced</span><b>{currency(x.invoiced)}</b></div><div><span>Next milestone</span><b>{x.next_milestone}</b><em>{x.milestone_due}</em></div></div></div>)}</div></> }
function Compliance(){ const [items,setItems]=useState([]); useEffect(()=>{api('/compliance').then(setItems)},[]); return <><h2>Compliance</h2><div className="tabs">Overview Training H&S Incidents RIDDOR Risk Assessments Policies Documents Obligations Calendar Score Audit</div><div className="card"><table><thead><tr><th>Type</th><th>Action</th><th>Owner</th><th>Due</th><th>Risk</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr><td>{i.type}</td><td>{i.title}</td><td>{i.owner}</td><td>{i.due_date}</td><td>{i.risk_rating}</td><td>{i.status}</td></tr>)}</tbody></table></div></> }
function Notifications(){ const [n,setN]=useState([]); useEffect(()=>{api('/notifications').then(setN)},[]); return <><h2>Notifications Centre</h2>{n.map(x=><div className="card notice"><Bell/><div><h3>{x.title}</h3><p>{x.module} · {x.body} · Due {x.due_date}</p></div></div>)}</> }
function Integrations(){ const [d,setD]=useState(null); useEffect(()=>{api('/integrations').then(setD)},[]); if(!d)return <Loader/>; return <><h2>Integrations</h2><div className="grid">{Object.entries(d.providers).map(([key,p])=><div className="card"><h3>{p.name}</h3><p>Normalises: {p.normalises.join(', ')}</p><button onClick={()=>api(`/integrations/${key}/sync`,{method:'POST'}).then(r=>alert(r.message))}>Configure / sync</button></div>)}</div></> }
function Concierge(){ const [q,setQ]=useState('What should I focus on this week?'), [a,setA]=useState(''); async function ask(){ const r=await api('/concierge',{method:'POST',body:JSON.stringify({question:q})}); setA(r.answer); } return <><h2>AI Concierge</h2><div className="card chat"><MessageSquare/><textarea value={q} onChange={e=>setQ(e.target.value)}/><button onClick={ask}>Ask Pulse</button>{a&&<div className="answer">{a}</div>}</div></> }
function Security(){ async function disable(){ const confirmed=confirm('Disabling MFA reduces your security score and enables mandatory 90-day password rotation. Continue?'); if(confirmed) await api('/security/mfa-disable',{method:'POST',body:JSON.stringify({confirmed:true})}).then(()=>alert('MFA disabled and audit record created.')); } return <><h2>Security</h2><div className="card"><h3>MFA enabled by default</h3><p>Only organisation administrators may disable MFA. If disabled, 90-day password rotation applies and an audit record is created.</p><button onClick={disable}>Disable MFA with confirmation</button></div></> }
function Admin({tab}){ const [orgs,setOrgs]=useState([]), [audit,setAudit]=useState([]); useEffect(()=>{api('/admin/organisations').then(setOrgs).catch(()=>{}); api('/admin/audit').then(setAudit).catch(()=>{})},[]); if(tab==='Audit Logs')return <><h2>Immutable Audit Logs</h2><div className="card"><table><tbody>{audit.map(a=><tr><td>{a.created_at}</td><td>{a.action}</td><td>{a.entity_type}</td><td>{a.ip_address}</td></tr>)}</tbody></table></div></>; return <><h2>Admin Centre</h2><div className="grid">{orgs.map(o=><div className="card"><h3>{o.name}</h3><p>Status: <b>{o.status}</b></p><p>Reverification due: {o.next_reverification_due||'Not set'}</p><p>Security: {o.security_score} · MFA {o.mfa_required?'Required':'Optional'}</p><select defaultValue={o.status} onChange={e=>api(`/admin/organisations/${o.id}/status`,{method:'PATCH',body:JSON.stringify({status:e.target.value})}).then(()=>alert('Status updated'))}>{['Pending Verification','Contract Sent','Awaiting Signature','Signed','Verified','Reverification Due','Suspended'].map(s=><option>{s}</option>)}</select></div>)}</div></> }
function Metric({label,value}){ return <div className="metric"><span>{label}</span><b>{value}</b></div> } function Loader(){return <div className="loader">Loading Pulse…</div>}
function App(){ const [me,setMe]=useState(null); useEffect(()=>{ if(token()) api('/me').then(setMe).catch(()=>localStorage.removeItem('pulse_token')); },[]); if(!me)return <Login onLogin={setMe}/>; return <Shell me={me} onLogout={()=>{localStorage.removeItem('pulse_token'); setMe(null)}}/> }

createRoot(document.getElementById('root')).render(<App/>);
